version: '3'

services:
  spring-boot-server:
    container_name: spring-boot-server
    restart: always
    build: .
#    depends_on:
#      - mssql
#      - redis
    ports:
      - "8080:8080"
#    links:
#      - mssql:mssql
#      - redis:redis
#    volumes:
#      - /Users/ubuntu/workspace/benapi_django:/Users/ubuntu/workspace/benapi_django
#    env_file: .env
    image: ghcr.io/chicheongweng/spring-boot-server:latest
    pull_policy: always

    environment:
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - SPRING_DATA_REDIS_PASSWORD=password
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://mssql:1433;encrypt=true;trustServerCertificate=true;hostNameInCertificate=*;loginTimeout=30;
      - SPRING_DATASOURCE_DRIVERCLASSNAME=com.microsoft.sqlserver.jdbc.SQLServerDriver
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=<YourStrong@Passw0rd>
      - APPLICATIONINSIGHTS_CONNECTION_STRING=InstrumentationKey=ec537f86-2187-4c12-b82e-fd0ff98ce011;IngestionEndpoint=https://eastasia-0.in.applicationinsights.azure.com/;LiveEndpoint=https://eastasia.livediagnostics.monitor.azure.com/
      - env=local
    networks:
      - dockerdatanetwork
    volumes:
      - ${HOME}/workspace/spring-boot-server:${HOME}/workspace/spring-boot-server


networks:
    dockerdatanetwork:
        external: true        
