version: '3'

services:
  spring-boot-server:
    container_name: spring-boot-server
    restart: no
    build: .
#    depends_on:
#      - mssql
#      - redis
    ports:
      - "8080:8080"
#    links:
#      - mssql:mssql
#      - redis:redis
#    volumes:
#      - /Users/ubuntu/workspace/benapi_django:/Users/ubuntu/workspace/benapi_django
#    env_file: .env
#    image: ghcr.io/chicheongweng/spring-boot-server:latest
    pull_policy: always

    environment:
      - APPLICATIONINSIGHTS_CONNECTION_STRING=InstrumentationKey=ec537f86-2187-4c12-b82e-fd0ff98ce011;IngestionEndpoint=https://eastasia-0.in.applicationinsights.azure.com/;LiveEndpoint=https://eastasia.livediagnostics.monitor.azure.com/
      - SPRING_PROFILES_ACTIVE=local
    networks:
      - dockerdatanetwork


networks:
    dockerdatanetwork:
        external: true        
