version: '3'

services:
  spring-boot-server:
    container_name: spring-boot-server
    restart: always
    build: .
#    depends_on:
#      - mssql
#      - redis
    ports:
      - "8080:8080"
#    links:
#      - mssql:mssql
#      - redis:redis
#    volumes:
#      - /Users/ubuntu/workspace/benapi_django:/Users/ubuntu/workspace/benapi_django
#    env_file: .env
#    image: ghcr.io/chicheongweng/spring-boot-server:latest
    pull_policy: always

    environment:
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - SPRING_DATA_REDIS_PASSWORD=password

      - HIBERNATE_DIALECT=org.hibernate.dialect.SQLServer2012Dialect
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://mssql:1433;encrypt=true;trustServerCertificate=true;hostNameInCertificate=*;loginTimeout=30;
      - SPRING_DATASOURCE_DRIVERCLASSNAME=com.microsoft.sqlserver.jdbc.SQLServerDriver
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=<YourStrong@Passw0rd>
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.SQLServer2012Dialect
      - SPRING_JPA_HIBERNATE_DLL_AUTO=create
      - SPRING_JPA_SHOW_SQL=true
      - AZURE_TENANT_ID=4f63aaa0-5612-4fe8-8175-9f9f4d26c7b4
      - AZURE_CLIENT_SECRET=Kpc8Q~w4m.t2e_qv3Gq6s-klnlnSiUB13-OpQdx.
      - AZURE_CLIENT_ID=f2077429-9df5-4176-880b-4638949ab6e1

      - APPLICATIONINSIGHTS_CONNECTION_STRING=InstrumentationKey=ec537f86-2187-4c12-b82e-fd0ff98ce011;IngestionEndpoint=https://eastasia-0.in.applicationinsights.azure.com/;LiveEndpoint=https://eastasia.livediagnostics.monitor.azure.com/
      - SPRING_PROFILES_ACTIVE=local
    networks:
      - dockerdatanetwork


networks:
    dockerdatanetwork:
        external: true        
